async function runTest() {
  try {
    console.log("Registering user...");
    const regRes = await fetch('http://localhost:5000/api/auth/register', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        username: 'testadmin_' + Date.now(),
        email: 'testadmin_' + Date.now() + '@example.com',
        password: 'password123',
        role: 'Admin'
      })
    });
    const regData = await regRes.json();
    if (!regRes.ok) throw new Error(JSON.stringify(regData));
    const token = regData.token;
    console.log("Registration successful! Token:", token.substring(0, 10) + "...");

    console.log("Creating a form...");
    const formRes = await fetch('http://localhost:5000/api/forms', {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({
        title: "Test Automated Form",
        description: "Auto generated by testing script",
        questions: [
          { id: "q1", type: "text", questionText: "What is your name?", required: true }
        ]
      })
    });
    const formData = await formRes.json();
    if (!formRes.ok) throw new Error(JSON.stringify(formData));
    const formId = formData._id;
    console.log(`Form created successfully! ID: ${formId}`);

    console.log("Submitting response...");
    const submitRes = await fetch(`http://localhost:5000/api/forms/${formId}/responses`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        answers: [{ questionId: "q1", value: "Antigravity Agent" }]
      })
    });
    const submitData = await submitRes.json();
    if (!submitRes.ok) throw new Error(JSON.stringify(submitData));
    console.log("Response submitted successfully!");

    console.log("Testing export...");
    const exportRes = await fetch(`http://localhost:5000/api/forms/${formId}/export`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${token}` }
    });
    const exportData = await exportRes.text();
    if (!exportRes.ok) throw new Error(exportData);
    console.log("Export successful! Contents:\n" + exportData);

    console.log("ALL TESTS PASSED SUCCESSFULLY!");
  } catch (err) {
    console.error("Test failed:");
    console.error(err);
  }
}

runTest();
